[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/schema",
    "crates/kabod",
    "bindings/python/bridge-schema",
    "bindings/python/kabod",
    "bindings/node/@bridgerust/kabod"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bridgerust/bridgerust"
authors = ["KOLOGO B Josias Yannick <hello@kologojosias.com>"]
