/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Point {
  x: number
  y: number
  constructor(x: number, y: number)
  distance(): number
}

export declare class Rectangle {
  width: number
  height: number
  constructor(width: number, height: number)
  area(): number
}

export declare function add(a: number, b: number): number

export declare function divide(a: number, b: number): number | null

export declare function greet(name: string): string

export declare function isEven(n: number): boolean

export declare function mightFail(value: number): number

export declare function multiply(a: number, b: number): number

export declare function sumNumbers(numbers: Array<number>): number
