/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BridgeQueue {
  constructor(maxRetries?: number | undefined | null, visibilityTimeoutMs?: number | undefined | null, retryBackoffMs?: number | undefined | null)
  static withAdapter(adapter: string, connectionUrl?: string | undefined | null, namespace?: string | undefined | null, maxRetries?: number | undefined | null, visibilityTimeoutMs?: number | undefined | null, retryBackoffMs?: number | undefined | null): BridgeQueue
  static redis(connectionUrl: string, namespace?: string | undefined | null, maxRetries?: number | undefined | null, visibilityTimeoutMs?: number | undefined | null, retryBackoffMs?: number | undefined | null): BridgeQueue
  static postgres(connectionUrl: string, namespace?: string | undefined | null, maxRetries?: number | undefined | null, visibilityTimeoutMs?: number | undefined | null, retryBackoffMs?: number | undefined | null): BridgeQueue
  enqueue(payload: string): number
  enqueueBatch(payloads: Array<string>): Array<number>
  dequeue(batchSize?: number | undefined | null): Array<QueueMessage>
  ack(id: number): boolean
  heartbeat(id: number): boolean
  extendLease(id: number, extraMs: number): boolean
  nack(id: number): boolean
  requeueDeadLetter(id: number): boolean
  stats(): QueueStats
  drainDeadLetter(): Array<QueueMessage>
}

export interface QueueMessage {
  id: number
  payload: string
  attempts: number
}

export interface QueueStats {
  ready: number
  delayed: number
  inFlight: number
  deadLetter: number
}
