[package]
name = "bridge-kabod-qdrant"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Qdrant adapter for Kabod Vector ORM"

[dependencies]
bridge-kabod-core = { path = "../../core" }
qdrant-client = "1.16"
async-trait = "0.1.89"
serde_json = "1.0.147"
