[package]
name = "bridge-schema-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "bridge_schema"
crate-type = ["cdylib"]

[dependencies]
bridge-schema = { path = "../../../crates/schema" }
pyo3 = { version = "0.27.2", features = ["extension-module"] }
