from typing import List, Optional, Dict, Any, Iterable, TypedDict

class EmbexError(Exception): ...
class ConfigError(EmbexError): ...
class DatabaseError(EmbexError): ...
class SerializationError(EmbexError): ...
class ValidationError(EmbexError): ...

class SearchOptions(TypedDict, total=False):
    limit: int
    offset: int
    filter: Dict[str, Any]
    include_metadata: bool
    include_vector: bool

class Point:
    id: str
    vector: List[float]
    metadata: Optional[Dict[str, Any]]
    
    def __init__(
        self, 
        id: str, 
        vector: List[float], 
        metadata: Optional[Dict[str, Any]] = None
    ) -> None: ...
    def dict(self) -> Dict[str, Any]: ...
    def model_dump(self) -> Dict[str, Any]: ...

class MetadataUpdate:
    id: str
    updates: Dict[str, Any]
    
    def __init__(self, id: str, updates: Dict[str, Any]) -> None: ...

class SearchResult:
    id: str
    score: float
    vector: Optional[List[float]]
    metadata: Optional[Dict[str, Any]]
    
    def dict(self) -> Dict[str, Any]: ...
    def model_dump(self) -> Dict[str, Any]: ...

class SearchResponse:
    results: List[SearchResult]
    aggregations: Dict[str, Any]
    
    def dict(self) -> Dict[str, Any]: ...
    def model_dump(self) -> Dict[str, Any]: ...
    def __len__(self) -> int: ...

class SearchBuilder:
    def limit(self, limit: int) -> "SearchBuilder": ...
    def offset(self, offset: int) -> "SearchBuilder": ...
    def include_vector(self, include: bool) -> "SearchBuilder": ...
    def include_metadata(self, include: bool) -> "SearchBuilder": ...
    def filter(self, filter: Dict[str, Any]) -> "SearchBuilder": ...
    def aggregation(self, agg_type: str) -> "SearchBuilder": ...
    async def execute(self) -> SearchResponse: ...

class QueryBuilder:
    def limit(self, limit: int) -> "QueryBuilder": ...
    def offset(self, offset: int) -> "QueryBuilder": ...
    def include_vector(self, include: bool) -> "QueryBuilder": ...
    def include_metadata(self, include: bool) -> "QueryBuilder": ...
    def filter(self, filter: Dict[str, Any]) -> "QueryBuilder": ...
    def aggregation(self, agg_type: str) -> "QueryBuilder": ...
    async def execute(self) -> SearchResponse: ...

class Collection:
    async def insert(self, points: List[Point]) -> None: ...
    async def insert_batch(
        self, 
        points: List[Point], 
        batch_size: Optional[int] = None, 
        parallel: Optional[int] = None
    ) -> None: ...
    async def insert_stream(
        self, 
        points: Iterable[Point], 
        batch_size: int = 1000
    ) -> None: ...
    async def search(
        self, 
        vector: List[float], 
        top_k: int = 10, 
        filter: Optional[Dict[str, Any]] = None,
        include_metadata: bool = True,
        include_vector: bool = False
    ) -> SearchResponse: ...
    async def query(
        self,
        vector: List[float],
        options: Optional[SearchOptions] = None
    ) -> SearchResponse: ...
    def build_search(self, vector: List[float]) -> SearchBuilder: ...
    def build_query(self) -> QueryBuilder: ...
    async def update_metadata(self, updates: List[MetadataUpdate]) -> None: ...
    async def delete(self, ids: List[str]) -> None: ...
    async def delete_collection(self) -> None: ...
    async def create(self, dimension: int, distance: str) -> None: ...
    async def create_auto(
        self, 
        dimension: Optional[int] = None, 
        distance: Optional[str] = None
    ) -> None: ...

class EmbexClient:
    def __init__(
        self, 
        provider: str, 
        url: str, 
        api_key: Optional[str] = None
    ) -> None: ...
    
    @staticmethod
    async def new_async(
        provider: str,
        url: str,
        api_key: Optional[str] = None
    ) -> "EmbexClient": ...
    
    def collection(self, name: str) -> Collection: ...
    async def run_migrations(self, migrations: List[Any]) -> None: ...
