/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Collection {
  /** Insert points into the collection. */
  insert(points: Array<Point>): Promise<void>
  /** Search for similar vectors. */
  query(vector: Array<number>, options?: SearchOptions | undefined | null): Promise<SearchResponse>
  /**
   * Search for similar vectors with direct parameters.
   *
   * @param vector - Query vector
   * @param topK - Number of results to return (default: 10)
   * @param filter - Optional metadata filter
   * @param includeMetadata - Whether to include metadata (default: true)
   * @param includeVector - Whether to include vectors (default: false)
   */
  search(vector: Array<number>, topK?: number | undefined | null, filter?: any | undefined | null, includeMetadata?: boolean | undefined | null, includeVector?: boolean | undefined | null): Promise<SearchResponse>
  /** Search using a builder pattern. */
  buildSearch(vector: Array<number>): SearchBuilder
  /** Query using a builder pattern (filter-only, no vector search). */
  buildQuery(): QueryBuilder
  /** Update metadata for points in the collection. */
  updateMetadata(updates: Array<MetadataUpdate>): Promise<void>
  delete(ids: Array<string>): Promise<void>
  deleteCollection(): Promise<void>
  create(dimension: number, distance: string): Promise<void>
  /**
   * Create the collection with optional dimension.
   *
   * For providers like Chroma that infer dimension from the first insert,
   * you can pass `undefined` for dimension. For other providers, dimension is required.
   *
   * @param dimension - Optional dimension. Use `undefined` for Chroma (infers from first insert).
   * @param distance - Distance metric ("cosine", "euclidean", or "dot").
   */
  createAuto(dimension?: number | undefined | null, distance?: string | undefined | null): Promise<void>
  insertBatch(points: Array<Point>, batchSize?: number | undefined | null, parallel?: number | undefined | null): Promise<void>
}

/** Main client for the Kabod vector database. */
export declare class KabodClient {
  /**
   * Create a new Kabod client.
   *
   * @param provider - The database provider (e.g., 'qdrant', 'pinecone').
   * @param url - The connection URL.
   * @param apiKey - Optional API key.
   */
  constructor(provider: string, url: string, apiKey?: string | undefined | null)
  /**
   * Create a new Kabod client with async initialization.
   * Required for providers like 'milvus', 'pgvector', and 'lancedb'.
   *
   * @param provider - The database provider.
   * @param url - The connection URL.
   * @param apiKey - Optional API key.
   */
  static newAsync(provider: string, url: string, apiKey?: string | undefined | null): Promise<KabodClient>
  collection(name: string): Collection
  /**
   * Run database migrations.
   *
   * @param migrations - Array of migration objects
   * {
   *   version: string,
   *   operations: [{ type: 'create_collection', schema: ... }, { type: 'delete_collection', name: ... }],
   *   down_operations: [...]
   * }
   */
  runMigrations(migrations: Array<MigrationInput>): Promise<void>
}

export declare class QueryBuilder {
  limit(limit: number): Promise<QueryBuilder>
  offset(offset: number): Promise<QueryBuilder>
  includeVector(include: boolean): Promise<QueryBuilder>
  includeMetadata(include: boolean): Promise<QueryBuilder>
  filter(filter: any): Promise<QueryBuilder>
  aggregation(aggType: string): Promise<QueryBuilder>
  execute(): Promise<SearchResponse>
}

export declare class SearchBuilder {
  limit(limit: number): Promise<SearchBuilder>
  offset(offset: number): Promise<SearchBuilder>
  includeVector(include: boolean): Promise<SearchBuilder>
  includeMetadata(include: boolean): Promise<SearchBuilder>
  filter(filter: any): Promise<SearchBuilder>
  aggregation(aggType: string): Promise<SearchBuilder>
  execute(): Promise<SearchResponse>
}

export interface MetadataUpdate {
  /** Point ID to update. */
  id: string
  /** Metadata updates to apply. */
  updates: Record<string, any>
}

export interface MigrationInput {
  version: string
  operations?: any
  downOperations?: any
}

/** A point in the vector database. */
export interface Point {
  id: string
  vector: Array<number>
  metadata?: Record<string, any>
}

export interface SearchOptions {
  /** Number of results to return. */
  limit?: number
  /** Metadata filter. */
  filter?: any
  /** Whether to include metadata in results. */
  includeMetadata?: boolean
  /** Whether to include vector in results. */
  includeVector?: boolean
  /** Pagination offset. */
  offset?: number
}

export interface SearchResponse {
  results: Array<SearchResult>
  aggregations: Record<string, any>
}

export interface SearchResult {
  id: string
  score: number
  vector?: Array<number>
  metadata?: Record<string, any>
}
