/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Collection {
  /** Insert points into the collection. */
  insert(points: Array<Point>): Promise<void>
  /** Search for similar vectors. */
  query(vector: Array<number>, options?: SearchOptions | undefined | null): Promise<SearchResponse>
  /** Search using a builder pattern. */
  search(vector: Array<number>): SearchBuilder
  delete(ids: Array<string>): Promise<void>
  deleteCollection(): Promise<void>
  create(dimension: number, distance: string): Promise<void>
  insertBatch(points: Array<Point>, batchSize?: number | undefined | null, parallel?: number | undefined | null): Promise<void>
}

/** Main client for the Kabod vector database. */
export declare class KabodClient {
  /**
   * Create a new Kabod client.
   *
   * @param provider - The database provider (e.g., 'qdrant', 'pinecone').
   * @param url - The connection URL.
   * @param apiKey - Optional API key.
   */
  constructor(provider: string, url: string, apiKey?: string | undefined | null)
  /**
   * Create a new Kabod client with async initialization.
   * Required for providers like 'milvus', 'pgvector', and 'lancedb'.
   *
   * @param provider - The database provider.
   * @param url - The connection URL.
   * @param apiKey - Optional API key.
   */
  static newAsync(provider: string, url: string, apiKey?: string | undefined | null): Promise<KabodClient>
  collection(name: string): Collection
}

export declare class SearchBuilder {
  limit(limit: number): Promise<SearchBuilder>
  offset(offset: number): Promise<SearchBuilder>
  includeVector(include: boolean): Promise<SearchBuilder>
  includeMetadata(include: boolean): Promise<SearchBuilder>
  filter(filter: any): Promise<SearchBuilder>
  execute(): Promise<SearchResponse>
}

/** A point in the vector database. */
export interface Point {
  id: string
  vector: Array<number>
  metadata?: Record<string, any>
}

export interface SearchOptions {
  /** Number of results to return. */
  limit?: number
  /** Metadata filter. */
  filter?: any
  /** Whether to include metadata in results. */
  includeMetadata?: boolean
  /** Whether to include vector in results. */
  includeVector?: boolean
  /** Pagination offset. */
  offset?: number
}

export interface SearchResponse {
  results: Array<SearchResult>
  aggregations: Record<string, any>
}

export interface SearchResult {
  id: string
  score: number
  vector?: Array<number>
  metadata?: Record<string, any>
}
